# This is a basic workflow to help you get started with Actions

name: Publish NuGet Package

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check-out code
        uses: actions/checkout@v2

      # Installs .NET Core
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          source-url: https://api.nuget.org/v3/index.json
          dotnet-version: 3.1.101
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}
          
      # Restore dependencies
      - name: Install dependencies
        run: dotnet restore src/

      # Publish NuGet package
      - name: Publish
        run: |
          mkdir __out
          dotnet build src/ -c Release
          dotnet pack src/ -c Release -o __out --no-restore
          dotnet nuget push "./__out/*.nupkg" --skip-duplicate --no-symbols true --api-key ${{secrets.NUGET_API_KEY}}
          rm -rf __out
